name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Adjust this to match the branch you want to trigger builds from.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0  # Specify the Ruby version you are using locally.

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll Site
      run: bundle exec jekyll build

    - name: Print Directory Structure (For Debugging)
      run: ls -R

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages  # The branch you want to deploy the built site to.
